fixtures:
  repositories:
    stunnel:
      repo: "https://github.com/Adaptavist/puppet-stunnel"
    stdlib:
      repo: "https://github.com/Adaptavist/puppet-stdlib"
  symlinks:
    stunnel_config: "#{source_dir}"
